# Notebook 1 – Introduction to NumPy

## NumPy Basics

This notebook covers the fundamental concepts of NumPy used in Data Science, Data Analytics, and AI/ML.

## 1. What is NumPy?

NumPy stands for Numerical Python. It is a Python library used for numerical and scientific computing.

It provides powerful arrays and mathematical functions that are faster and more efficient than normal Python lists.

NumPy is commonly used in Data Science and Machine Learning for numerical calculations and data processing.

### Real-World Example

Imagine we have the daily sales of a shop:

100, 150, 200, 175, 300

Instead of processing each value separately, NumPy allows us to store these values in an array and perform calculations on all values efficiently.

This is useful when working with large datasets.

### Business Example

A company may have monthly sales data for thousands of products.

NumPy can be used to calculate total sales, average sales, minimum sales, maximum sales, and other numerical measurements efficiently.

### AI/ML Example

Machine Learning models work with numerical data.

NumPy arrays can store features such as age, salary, experience, and purchase amount before the data is provided to a Machine Learning model.

In [1]:
import numpy as np

print("NumPy imported successfully")

NumPy imported successfully


## 2. Why NumPy?

NumPy is useful because it provides fast numerical operations, efficient memory usage, multidimensional arrays, and many mathematical functions.

It is widely used as a foundation for libraries such as Pandas, Scikit-learn, and other Data Science tools.

In [2]:
python_list = [1, 2, 3, 4, 5]

numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List:", python_list)
print("NumPy Array:", numpy_array)

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


### Explanation

A Python list can store different types of objects, while a NumPy array is designed mainly for numerical data.

NumPy arrays support fast mathematical operations and are more efficient for numerical computations.

## 3. NumPy Array (ndarray)

A NumPy array is a data structure used to store multiple values efficiently.

NumPy arrays can be one-dimensional, two-dimensional, or multidimensional.

The NumPy array is called `ndarray`, which means N-dimensional array.

### Example

Imagine a classroom with the marks of five students:

45, 67, 78, 89, 92

We can store these marks in a NumPy array and easily perform calculations such as finding the average, highest mark, or lowest mark.

In AI/ML, NumPy arrays are commonly used to store numerical features and data.

In [8]:
import numpy as np

marks = np.array([45, 67, 78, 89, 92])

print("Marks:", marks)
print("Type:", type(marks))

Marks: [45 67 78 89 92]
Type: <class 'numpy.ndarray'>


### Output Explanation

The output shows the values stored in the NumPy array.

The `type()` function confirms that `marks` is a NumPy `ndarray`.

This array can now be used for numerical operations efficiently.

## 4. Creating Arrays

NumPy provides different functions for creating arrays.

### Example

Suppose we need to create arrays for marks, initial values, or a sequence of numbers.

Instead of manually creating every value, NumPy provides functions that can generate these arrays quickly.

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros(5)
arr3 = np.ones(5)
arr4 = np.arange(1, 6)
arr5 = np.linspace(1, 10, 5)

print("array:", arr1)
print("zeros:", arr2)
print("ones:", arr3)
print("arange:", arr4)
print("linspace:", arr5)

array: [1 2 3 4 5]
zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]
arange: [1 2 3 4 5]
linspace: [ 1.    3.25  5.5   7.75 10.  ]


### Output Explanation
Some commonly used methods are:

- `np.array()` – creates an array from existing data
- `np.zeros()` – creates an array filled with zeros
- `np.ones()` – creates an array filled with ones
- `np.arange()` – creates values within a specified range
- `np.linspace()` – creates evenly spaced values

## 5. Dimensions

The dimension of an array tells us the number of axes in the array.

A 1D array contains a single axis, while a 2D array contains rows and columns.

### Example

A list of student marks is a 1D array.

A table containing student marks for different subjects is a 2D array.

In [11]:
arr_1d = np.array([10, 20, 30, 40])

arr_2d = np.array([
    [10, 20],
    [30, 40]
])

print("1D dimensions:", arr_1d.ndim)
print("2D dimensions:", arr_2d.ndim)

1D dimensions: 1
2D dimensions: 2


### Output Explanation

The `ndim` attribute returns the number of dimensions.

The first array has 1 dimension, and the second array has 2 dimensions.

## 6. Shape

The `shape` attribute tells us the size of an array along each dimension.

For a 2D array, the shape is represented as `(rows, columns)`.

### Example

A dataset containing 3 students and 2 subjects has 3 rows and 2 columns.

Therefore, its shape is `(3, 2)`.

In [12]:
arr = np.array([
    [80, 90],
    [70, 85],
    [95, 88]
])

print("Shape:", arr.shape)

Shape: (3, 2)


### Output Explanation

The output `(3, 2)` means the array contains 3 rows and 2 columns.

## 7. Size

The `size` attribute returns the total number of elements in a NumPy array.

It counts all elements across all dimensions.

### Example

If an array has 3 rows and 2 columns, it contains a total of 6 elements.

The `size` attribute can be used to find this total.

In [13]:
arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("Total elements:", arr.size)

Total elements: 6


### Output Explanation

The output is `6` because the array contains 3 rows × 2 columns = 6 elements.

## 8. Data Types

The `dtype` attribute tells us the type of data stored in a NumPy array.

Common types include integers, floating-point numbers, Boolean values, and strings.

### Example

If an array contains student ages, the values can be stored as integers.

If an array contains prices, the values may be stored as floating-point numbers.

In [25]:
ages = np.array([20, 21, 22, 23])
prices = np.array([99.5, 150.75, 200.25])

print("Age data type:", ages.dtype)
print("Price data type:", prices.dtype)

Age data type: int64
Price data type: float64


### Output Explanation

The first array contains integer values, so NumPy identifies its type as an integer.

The second array contains decimal values, so NumPy identifies its type as a floating-point number.

## 9. Indexing

Indexing is used to access individual elements from a NumPy array.

NumPy uses zero-based indexing, so the first element has index `0`.

### Example

Consider the array `[10, 20, 30, 40, 50]`.

The value `10` is at index 0, while `30` is at index 2.

Indexing allows us to access specific values from the array.

In [15]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

First element: 10
Third element: 30
Last element: 50


### Output Explanation

`arr[0]` returns the first element, `arr[2]` returns the third element, and `arr[-1]` returns the last element.

## 10. Slicing

Slicing is used to extract a portion of elements from a NumPy array.

The basic syntax is `array[start:stop]`, where the stop index is excluded.

### Example

If we have sales data for five days, we can use slicing to select sales from only the first few days.

This is useful when working with portions of datasets.

In [16]:
sales = np.array([100, 200, 150, 300, 250])

print("First three values:", sales[0:3])
print("Last two values:", sales[-2:])

First three values: [100 200 150]
Last two values: [300 250]


### Output Explanation

`0:3` selects elements from index 0 up to index 2.

`-2:` selects the last two elements of the array.

## 11. Reshaping

Reshaping changes the structure of an array without changing its data.

The `reshape()` method is used to convert an array into a different shape.

### Example

Suppose we have 6 values stored in a 1D array.

We can reshape these 6 values into 2 rows and 3 columns for representing tabular data.

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape(2, 3)

print("Original array:", arr)
print("Reshaped array:")
print(reshaped_arr)

Original array: [1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


### Output Explanation

The original array contains 6 elements.

After reshaping, the same 6 elements are arranged into 2 rows and 3 columns.

## 12. Flatten

The `flatten()` method converts a multidimensional array into a one-dimensional array.

It creates a new copy of the data.

### Example

A 2D dataset may contain rows and columns.

Flattening can convert this structure into a single sequence of values when a 1D representation is required.

In [18]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat_arr = arr.flatten()

print("Original array:")
print(arr)

print("Flattened array:")
print(flat_arr)

Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


### Output Explanation

The original array has two dimensions.

`flatten()` converts it into a single 1D array containing all six values.

## 13. Copy vs View

A copy creates a separate array with its own data.

A view creates another way to access the same underlying data.

Changes made to a view can affect the original array, while changes to a copy do not affect the original.

### Example

Think of a copy as making a photocopy of a document.

A view is like looking at the same original document from another window.

Changing the photocopy does not change the original, but changing the original through a view can affect the same data.

In [19]:
arr = np.array([10, 20, 30, 40])

copy_arr = arr.copy()
view_arr = arr.view()

copy_arr[0] = 100
view_arr[1] = 200

print("Original array:", arr)
print("Copy:", copy_arr)
print("View:", view_arr)

Original array: [ 10 200  30  40]
Copy: [100  20  30  40]
View: [ 10 200  30  40]


### Output Explanation

Changing the copy does not change the original array.

Changing the view changes the original array because both share the same underlying data.

## 14. Broadcasting

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

It allows a smaller array or scalar value to be automatically applied across a larger array without manually repeating the values.

### Example

Suppose every product price needs to be increased by 10%.

Instead of adding 10 separately to every price, NumPy can add 10 to the entire array at once using broadcasting.

In [20]:
prices = np.array([100, 200, 300, 400])

new_prices = prices + 10

print("Original prices:", prices)
print("New prices:", new_prices)

Original prices: [100 200 300 400]
New prices: [110 210 310 410]


### Output Explanation

NumPy automatically applies the value `10` to every element of the array.

This is broadcasting and avoids writing a loop for each element.

## 15. Array Operations

NumPy allows us to perform arithmetic operations directly on arrays.

Common operations include addition, subtraction, multiplication, and division.

### Example

Suppose we have the sales quantities and prices of different products.

We can multiply the arrays directly to calculate the total value for each product.

In [21]:
quantity = np.array([2, 3, 4])
price = np.array([100, 200, 150])

total = quantity * price

print("Total value:", total)

Total value: [200 600 600]


### Output Explanation

NumPy multiplies corresponding elements from both arrays.

The result is `[200, 600, 600]`, representing the total value of each product.

## 16. Universal Functions (ufuncs)

Universal functions, or ufuncs, are NumPy functions that perform operations element-by-element on arrays.

Examples include `np.sqrt()`, `np.square()`, `np.exp()`, and `np.abs()`.

### Example

Suppose we have several numerical values and want to calculate their square roots.

Instead of processing each value separately, a NumPy ufunc can perform the operation on the entire array.

In [22]:
numbers = np.array([4, 9, 16, 25])

square_roots = np.sqrt(numbers)

print("Numbers:", numbers)
print("Square roots:", square_roots)

Numbers: [ 4  9 16 25]
Square roots: [2. 3. 4. 5.]


### Output Explanation

`np.sqrt()` calculates the square root of each element.

The output contains `[2, 3, 4, 5]`, showing that the operation was applied element-by-element.