# Notebook 2 – NumPy Mathematical Operations

## 1. Sum

The `np.sum()` function calculates the total of all elements in a NumPy array.

It can also calculate the sum along a specific axis.

### Example

Suppose a shop has daily sales of 100, 200, 150, and 250.

We can use `np.sum()` to calculate the total sales.

In AI/ML, summation can be used when calculating totals or aggregating numerical features.

In [1]:
import numpy as np

sales = np.array([100, 200, 150, 250])

total_sales = np.sum(sales)

print("Total sales:", total_sales)

Total sales: 700


### Output Explanation

The output is `700` because:

100 + 200 + 150 + 250 = 700

Therefore, the total sales are 700.

## 2. Mean

The mean is the average value of a set of numbers.

NumPy provides `np.mean()` to calculate the arithmetic average of array elements.

### Example

Suppose the marks of five students are 60, 70, 80, 90, and 100.

The mean gives us the average mark of the students.

In [2]:
marks = np.array([60, 70, 80, 90, 100])

average = np.mean(marks)

print("Mean:", average)

Mean: 80.0


### Output Explanation

The output is `80.0`.

The mean is calculated as:

(60 + 70 + 80 + 90 + 100) / 5 = 80

So, the average mark is 80.

## 3. Median

The median is the middle value when the data is arranged in sorted order.

The `np.median()` function is used to calculate the median of an array.

### Example

Consider the salaries:

25000, 30000, 35000, 40000, 100000

The median represents the middle salary and is less affected by the extremely high salary.

In [3]:
salaries = np.array([25000, 30000, 35000, 40000, 100000])

median_salary = np.median(salaries)

print("Median salary:", median_salary)

Median salary: 35000.0


### Output Explanation

The output is `35000.0`.

The middle value after sorting the data is 35000.

Median is useful when the dataset contains extreme values or outliers.

## 4. Variance

Variance measures how much the values in a dataset differ from their mean.

A higher variance means the values are more spread out, while a lower variance means they are closer to the mean.

### Example

Consider two groups of student marks.

If the marks are very close to each other, the variance will be low.

If the marks are widely different, the variance will be high.

In [5]:
marks = np.array([10, 20, 30, 40, 50])

variance = np.var(marks)

print("Variance:", variance)

Variance: 200.0


### Output Explanation

The output is `200.0`.

Variance measures the average squared distance of the values from their mean.

A larger variance indicates greater spread in the data.

## 5. Standard Deviation

Standard deviation measures how much the values differ from the mean.

It is the square root of variance and is expressed in the same unit as the original data.

### Example

If the standard deviation of employee salaries is small, most salaries are close to the average salary.

If it is large, salaries are more widely spread.

In [6]:
salaries = np.array([30000, 32000, 31000, 33000, 35000])

std_dev = np.std(salaries)

print("Standard deviation:", std_dev)

Standard deviation: 1720.4650534085254


### Output Explanation

The output represents how much the salaries typically vary from their mean.

A smaller standard deviation means the salaries are relatively close to the average.

## 6. Minimum

The `np.min()` function returns the smallest value in a NumPy array.

It is useful for finding the lowest value in numerical data.

### Example

A company can use minimum sales to identify the day with the lowest sales amount.

In [7]:
sales = np.array([500, 300, 700, 200, 600])

minimum_sales = np.min(sales)

print("Minimum sales:", minimum_sales)

Minimum sales: 200


### Output Explanation

The output is `200`.

It is the smallest value present in the sales array.

## 7. Maximum

The `np.max()` function returns the largest value in a NumPy array.

It is useful for identifying the highest value in numerical data.

### Example

A business can use maximum sales to identify its highest-selling day.

In [8]:
sales = np.array([500, 300, 700, 200, 600])

maximum_sales = np.max(sales)

print("Maximum sales:", maximum_sales)

Maximum sales: 700


### Output Explanation

The output is `700`.

It is the largest value in the sales array.

## 8. Argmin

The `np.argmin()` function returns the index position of the smallest value in an array.

It returns the position, not the actual minimum value.

### Example

If we have daily sales data, `argmin()` can help identify the position of the day with the lowest sales.

In [9]:
sales = np.array([500, 300, 700, 200, 600])

index = np.argmin(sales)

print("Index of minimum value:", index)
print("Minimum value:", sales[index])

Index of minimum value: 3
Minimum value: 200


### Output Explanation

The output index is `3` because the smallest value, 200, is located at index 3.

`argmin()` gives the position of the minimum value.

## 9. Argmax

The `np.argmax()` function returns the index position of the largest value in an array.

It returns the position rather than the actual maximum value.

### Example

A business can use `argmax()` to find the position of the highest sales value.

In [10]:
sales = np.array([500, 300, 700, 200, 600])

index = np.argmax(sales)

print("Index of maximum value:", index)
print("Maximum value:", sales[index])

Index of maximum value: 2
Maximum value: 700


### Output Explanation

The output index is `2` because the highest value, 700, is located at index 2.

`argmax()` gives the position of the maximum value.

## 10. Percentile

A percentile tells us the value below which a certain percentage of observations fall.

NumPy provides `np.percentile()` to calculate percentiles.

### Example

A company can use the 90th percentile of customer spending to understand the spending level below which 90% of customers fall.

Percentiles are useful for understanding the distribution of data.

In [11]:
spending = np.array([100, 200, 300, 400, 500])

p90 = np.percentile(spending, 90)

print("90th percentile:", p90)

90th percentile: 460.0


### Output Explanation

The output represents the value at the 90th percentile.

Percentiles are commonly used to analyze distributions, thresholds, and extreme values.

## 11. Dot Product

The dot product multiplies corresponding elements of two arrays and then adds the results.

NumPy provides `np.dot()` to calculate the dot product.

### Example

Suppose a product has quantities and prices.

The dot product can calculate the total value by multiplying each quantity by its corresponding price and adding the results.

In [12]:
quantity = np.array([2, 3, 4])
price = np.array([100, 200, 150])

total_value = np.dot(quantity, price)

print("Total value:", total_value)

Total value: 1400


### Output Explanation

The calculation is:

(2 × 100) + (3 × 200) + (4 × 150) = 1400

Therefore, the dot product is `1400`.

## 12. Matrix Multiplication

Matrix multiplication combines two matrices using mathematical multiplication rules.

NumPy provides `np.matmul()` and the `@` operator for matrix multiplication.

### Example

Matrix multiplication is widely used in Machine Learning and Deep Learning.

For example, neural networks use matrix multiplication when calculating values between layers.

In [13]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(A, B)

print("Matrix multiplication:")
print(result)

Matrix multiplication:
[[19 22]
 [43 50]]


### Output Explanation

The matrices are multiplied according to matrix multiplication rules.

The resulting matrix is:

[[19 22]
 [43 50]]

The result has 2 rows and 2 columns.

## 13. Transpose

Transpose changes the rows of a matrix into columns and the columns into rows.

NumPy provides `.T` and `np.transpose()` for transposing arrays.

### Example

A dataset may have observations as rows and features as columns.

Transposing the array changes this orientation so that rows become columns.

In [14]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed = arr.T

print("Original:")
print(arr)

print("Transposed:")
print(transposed)

Original:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]


### Output Explanation

The original array has 2 rows and 3 columns.

After transposing, it has 3 rows and 2 columns.

## 14. Basic Linear Algebra Operations

NumPy provides several functions for basic linear algebra operations.

These include matrix multiplication, dot products, transpose, inverse, and solving linear equations.

### Example

Linear algebra is an important part of Machine Learning.

Operations on vectors and matrices are used in regression, neural networks, dimensionality reduction, and many other ML algorithms.

In [17]:
A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([
    [4, 2],
    [1, 5]
])

product = A @ B
transpose = A.T

print("Matrix multiplication:")
print(product)

print("\nTranspose:")
print(transpose)

Matrix multiplication:
[[ 9  9]
 [ 7 17]]

Transpose:
[[2 1]
 [1 3]]


### Output Explanation

The `@` operator performs matrix multiplication.

The `.T` attribute transposes the matrix by converting rows into columns.

These operations are fundamental in many Machine Learning algorithms.